[package]
name = "advent-of-code-2018"
version = "0.1.0"
authors = ["Jamie Seward <jamie.d.seward@gmail.com>"]

[lib]
bench = false

[dependencies]
rust-crypto = "0.2.36"
aoc-runner = "0.1.0"
aoc-runner-derive = "0.1.0"
regex = "1"